SELECT DISTINCT ?item ?page_title ?itemLabel ?countyLabel ?gnis WHERE {
  VALUES ?types { wd:Q5086782 wd:Q17205774 }
  ?item wdt:P31 ?types .
  OPTIONAL { ?item wdt:P590 ?gnis. }
  OPTIONAL { ?item wdt:P131 ?county. }
  OPTIONAL {
    ?article schema:about ?item.
    ?article schema:isPartOf <https://en.wikipedia.org/>.
    ?article schema:name ?page_title.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}